---
- hosts: localhost
  tasks:
    - name: Execute the python script to prepare inventory file from excel sheets.
      shell: python3.8 /ansible_dir/playbooks/get_inventory_refactored.py {{day}}
      register: xl_op
    - debug:
            msg: "{{xl_op}}"

  # The above playbook is executed
  # a) In the terminal by ansible-playbook ansible_inventory.yaml -e "day_of_patching='Day1'"
  # b) In the ansible tower by giving day_of_patching in extra variables section and also enabling prompt on launch option, so for every execution it prompts for a value to be given
