---
- name: Master Patching Activities
  hosts: windows
  gather_facts: true
  ignore_errors: true

  pre_tasks:
    - set_fact:
        date_time: "{{'%Y-%m-%d_%HH-%MM-%SS' | strftime }}"
      run_once: true
      delegate_to: localhost

  # - name: Send patching starting mail to team
  #   mail:
  #    host: localhost
  #    port: 25
  #    to: Vishnuvardhan <vishnu@example.com>
  #    cc: Sarika Marathe <sarika@example.com>
  #    subject: Patching is starting
  #    body: Hello Team!  patching is starting
  #   run_once: true
  #   delegate_to: localhost

  tasks:
    - include_tasks: windows_patching.yaml

  post_tasks:
  # - name: Send patching report to team
  #   mail:
  #     host: localhost
  #     port: 25
  #     to: Vishnuvardhan <vishnu@example.com>
  #     cc: Sarika Marathe <sarika@example.com>
  #     subject: patching report
  #     body: Hi team! Please find the attached patching report
  #     attach: /tmp/ansible_dir/patching_output_files/{{date_time}}_windows_patch.txt
  #   run_once: true
  #   delegate_to: localhost
