---
- name: Master Pre Patch Activities
  hosts: windows
  gather_facts: true
  ignore_errors: true

  tasks:       
  - set_fact:
      date_time: "{{ ansible_date_time.date}}_{{ansible_date_time.hour}}H-{{ansible_date_time.minute}}M-{{ansible_date_time.second}}S"                                                                                     
  - include_tasks: pre_patch.yaml
           
