---
- name: Master Pre Patch Activities
  hosts: all
  gather_facts: true
  ignore_errors: true

  pre_tasks:
    - set_fact:
        date_time: "{{'%Y-%m-%d_%HH-%MM-%SS' | strftime }}"
      run_once: true
      delegate_to: localhost

    - name: Creating directory to store windows updates log files in localhost
      file:
        path: /ansible_dir/win_updates_files/{{date_time}}
        state: directory
      run_once: true
      delegate_to: localhost

  # - name: Send pre-patch starting mail to team
  #   mail:
  #    host: localhost
  #    port: 25
  #    to: Vishnuvardhan <vishnu@example.com>
  #    cc: Sarika Marathe <sarika@example.com>
  #    subject: Pre-Patch is starting
  #    body: Hello Team!  Pre-patch is starting
  #   run_once: true
  #   delegate_to: localhost

  tasks:
    - include_tasks: pre_patch.yaml

  post_tasks:
  - name: check pre-patch log file exists
    stat:
      path: "/ansible_dir/pre_patch_output_files/{{date_time}}_pre_patch.txt"
      run_once: true
    register: pre_patch_log
    delegate_to: localhost 

  - name: Create pre-patch log file if doesn't exist
    file:
           path: "/ansible_dir/pre_patch_output_files/{{date_time}}_pre_patch.txt"
           state: touch
    become: yes
    run_once: true  
    when: pre_patch_log.stat.exists == false
    delegate_to: localhost

  - name: lineinfile module 
    lineinfile:  
     line: "Unreachable hosts: {{ansible_play_hosts_all | difference(ansible_play_hosts) }}"
     dest: /ansible_dir/pre_patch_output_files/{{date_time}}_pre_patch.txt 
     insertbefore: EOF
    delegate_to: localhost     
  # - name: Send pre-patch report to team
  #   mail:
  #     host: localhost
  #     port: 25
  #     to: Vishnuvardhan <vishnu@example.com>
  #     cc: Sarika Marathe <sarika@example.com>
  #     subject: Pre-patch report
  #     body: Hi team! Please find the attached pre-patch report
  #     attach: /tmp/ansible_dir/pre_patch_output_files/{{date_time}}_pre_patch.txt
  #   run_once: true
  #   delegate_to: localhost
