---
- hosts: localhost
  gather_facts: false
  tasks:
  - setup:
          filter: "ansible_date_time"
  - set_fact:
          s_t: "{{ansible_date_time.iso8601[:19] }}"
  - wait_for:
          timeout: 10
  - setup:   
     filter: "ansible_date_time"
  - set_fact:
          r_t: "{{ ((ansible_date_time.iso8601[:19] | to_datetime('%Y-%m-%dT%H:%M:%S')) - (s_t | to_datetime('%Y-%m-%dT%H:%M:%S'))).seconds }}"
  - debug:
          msg: "{{ r_t }}"
